services:
  postgres:
    container_name: muralis_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Muralis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
